# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('course_offered_in', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=100)),
                ('course_length', models.IntegerField()),
                ('course_units', models.IntegerField()),
                ('course_convenor', models.CharField(max_length=100)),
                ('course_convenor_email', models.EmailField(max_length=254)),
                ('course_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Spec_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(max_length=10)),
                ('major_type', models.IntegerField()),
                ('major_title', models.CharField(max_length=200)),
                ('major_min_units', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Programs')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Spec_Major'),
        ),
        migrations.AddField(
            model_name='course_offering',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Courses'),
        ),
    ]
